Trigger Engine: fix deployment strategy
astarte-platform/astarte-kubernetes-operator pull request #156
Opened 2020-09-21 12:45 UTC by matt-mazzucato

Default Trigger Engine's deployment strategy to Recreate

2020-09-21 12:48 UTC, drf requested changes

2020-09-21 12:48 UTC, drf commented on pkg/controller/astarte/reconcile/utils.go
> +	case component == apiv1alpha1.TriggerEngine:
join it together with the previous case.

`case component == apiv1alpha1.DataUpdaterPlant, component == apiv1alpha1.TriggerEngine:`

2020-09-21 12:51 UTC, rbino requested changes

2020-09-21 12:51 UTC, rbino commented on pkg/controller/astarte/reconcile/utils.go
> +	case component == apiv1alpha1.TriggerEngine:
Just do
```go
case component == apiv1alpha1.DataUpdaterPlant, component == apiv1alpha1.TriggerEngine:
```
above

2020-09-22 08:59 UTC, drf approved these changes

2020-09-22 08:59 UTC, merged