Deployment strategy for DUP and TE is forced to Recreate
astarte-platform/astarte-kubernetes-operator pull request #160
Opened 2020-10-06 10:55 UTC by matt-mazzucato

Both DUP and TE must be deployed with deployment strategy set to Recreate: therefore, override user preferences and force the desired strategy.

2020-10-06 10:58 UTC, rbino approved these changes

2020-10-06 11:01 UTC, bettio approved these changes

2020-10-06 11:01 UTC, bettio requested changes
Please, add this to the CHANGELOG file

2020-10-07 13:08 UTC, bettio approved these changes

2020-10-07 13:08 UTC, merged