Handle erlang cookie for rabbitmq
astarte-platform/astarte-kubernetes-operator pull request #286
Opened 2022-05-26 11:51 UTC by matt-mazzucato

In rabbitmq 3.8, setting the erlang cookie with an env variable is
deprecated and, starting from 3.9, it will not be supported (see
https://github.com/docker-library/rabbitmq/blob/master/docker-entrypoint-3.8.sh#L199).
Thus, mount the erlang cookie as a volume.

2022-05-27 10:41 UTC, Annopaolo approved these changes

2022-06-08 16:28 UTC, rbino requested changes

2022-06-08 16:28 UTC, rbino commented on lib/reconcile/rabbitmq.go
> +					"cp /erlang-cookie-secret/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie " +
I  think also the first command should be followed by `&&` instead of `;`, otherwise if it fails, it would do so silently

2022-06-08 16:28 UTC, rbino commented on lib/reconcile/rabbitmq.go
> +					"&& chmod 400 /var/lib/rabbitmq/.erlang.cookie ; ",
No need for `;` at the end

2022-06-23 09:09 UTC, rbino approved these changes

2022-06-23 09:23 UTC, bettio approved these changes

2022-06-23 09:23 UTC, merged