Change storage version for resources in api.astarte-platform.org
astarte-platform/astarte-kubernetes-operator pull request #297
Opened 2022-08-17 10:44 UTC by matt-mazzucato

- Resources in the api.astarte-platform.org group are now stored in the v1alpha2 version
- Add a deprecation notice for Astarte's and Flow's v1alpha1 api versions
- Add a deprecation notice for AstarteVoyagerIngress (the API will no longer be available starting from Astarte Operator v1.2+)

2022-08-17 15:02 UTC, Annopaolo requested changes

2022-08-18 13:42 UTC, matt-mazzucato commented on lib/migrate/migrate.go
>  // The purpose of this package is solely the migration of the old operator's flaky CR to the shiny new, stable,
Let's tackle this in a dedicated PR

2022-08-24 09:21 UTC, Annopaolo requested changes

2022-08-24 09:21 UTC, Annopaolo commented on apis/api/v1alpha1/conversion.go
> +	return nil
Could we shorten those lines like this? If there is no error, `nil` will be returned anyway.
```go
return Convert_v1alpha1_Astarte_To_v1alpha2_Astarte(src, dst, nil)
```
The same applies to all other conversion functions in this file.

2022-08-25 13:57 UTC, Annopaolo approved these changes

2022-09-23 09:33 UTC, rbino approved these changes

2022-09-27 13:49 UTC, Annopaolo commented on CHANGELOG.md
> +- Add deprecation notice for v1alpha1 resources (i.e. Astarte and AstarteFlow).
Add also here `(will be unavailable starting from Astarte Operator v1.2+).`

2022-09-27 14:23 UTC, Annopaolo approved these changes

2022-09-27 14:23 UTC, Annopaolo commented on CHANGELOG.md
> +  AstarteFlow and AstarteVoyagerIngresses will be unavailable starting from Astarte Operator v1.2+).
Remove leftover `)`

2022-09-27 15:14 UTC, rbino approved these changes

2022-09-29 09:17 UTC, merged