Prepare v22.11.00-rc.0
astarte-platform/astarte-kubernetes-operator pull request #313
Opened 2022-11-29 16:38 UTC by Annopaolo

2022-11-29 17:45 UTC, matt-mazzucato requested changes
One last thing is missing: please, change the `test/helm/astarte.yaml` so that the used apiVersion is `v1alpha2`.
Except for this, everything LGTM.

2022-11-29 17:49 UTC, matt-mazzucato approved these changes

2022-11-30 09:37 UTC, rbino commented on test/e2e11/astarte_test.go
> +  Copyright 2020 Ispirata Srl
Fix year and company

2022-11-30 09:37 UTC, rbino commented on test/e2e11/deploy_astarte_1.1_test.go
> +  Copyright 2020 Ispirata Srl
Fix year and company

2022-11-30 10:17 UTC, merged