Restart the broker when its SSLListener secret changes
astarte-platform/astarte-kubernetes-operator pull request #323
Opened 2023-03-29 16:05 UTC by Annopaolo

When the TLS certificate is deleted or created, VerneMQ pods are restarted so that they correctly retrieve the new file (if present). In order to do that, the operator is now also able to delete collections of pods.
Fix #317.

2023-03-31 15:14 UTC, matt-mazzucato requested changes

2023-04-03 12:20 UTC, Annopaolo commented on lib/reconcile/vernemq.go
> +func maybeDeleteVerneMQPods(cr *apiv1alpha2.Astarte, c client.Client) error {
Added [some lines above](https://github.com/astarte-platform/astarte-kubernetes-operator/pull/323/commits/d4619d7c68b199d1f5df158a55fe3157b523f8bc#diff-40d8a899e7fdda68dbafcddd699bc5d3adfa5b94cddba7e7e8233dc5a4a2fb02R127-R129).

2023-05-10 10:17 UTC, matt-mazzucato approved these changes

2023-05-10 10:29 UTC, matt-mazzucato approved these changes

2023-05-10 10:39 UTC, merged